---
- name: Example NETCONF playbook
  hosts: csr
  connection: netconf
  gather_facts: no

  vars:
    ansible_network_os: cisco.ios.ios

  tasks:
    - name: Get device facts using NETCONF
      cisco.ios.ios_netconf_config:
        xml: |
          <filter>
            <interfaces xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces">
              <interface>
                <name>GigabitEthernet1</name>
              </interface>
            </interfaces>
          </filter>
      register: interface_info
    - name: Print the received XML data
      debug:
        var: interface_info.stdout
