---
- name: Get Running Configuration with a Raw NETCONF RPC
  hosts: csr
  connection: netconf
  gather_facts: no

  tasks:
    - name: Execute a <get-config> RPC for the native model
      ansible.netcommon.netconf_rpc:
        rpc: get-config
        content: |
          <source>
            <running/>
          </source>
          <filter>
            <native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native"/>
          </filter>
      register: running_config_output

    - name: Print the full RPC reply
      debug:
        # --- THIS IS THE FINAL FIX ---
        # The data is in the 'stdout' key.
        var: running_config_output.stdout
