---
- name: Get and Save Running Configuration via NETCONF
  hosts: csr
  # We need to run the final 'copy' task on the control node (AWX itself)
  # so we delegate that specific task.
  connection: netconf
  gather_facts: no

  tasks:
    - name: Execute a <get-config> RPC for the native model
      ansible.netcommon.netconf_rpc:
        rpc: get-config
        content: |
          <source>
            <running/>
          </source>
          <filter>
            <native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native"/>
          </filter>
      register: running_config_output

    - name: Save the full running configuration to a file
      ansible.builtin.copy:
        # The 'content' parameter takes the data directly from our variable.
        content: "{{ running_config_output.stdout }}"
        # This is the destination file path *inside the AWX container*.
        # We use the inventory_hostname variable to create a unique filename for each host.
        dest: "/runner/artifacts/{{ inventory_hostname }}_running_config.xml"
      # This task needs to run on the AWX node, not on the router.
      delegate_to: localhost

    - name: Display a confirmation message
      debug:
        msg: "Successfully retrieved and saved the configuration to /runner/artifacts/{{ inventory_hostname }}_running_config.xml"
