---
- name: Configure Cisco router via SSH
  hosts: csr  # This should match an entry in your inventory
  connection: ansible.netcommon.network_cli
  gather_facts: no

  vars:
    ansible_network_os: cisco.ios.ios
    ansible_user: "your_ssh_username"
    ansible_password: "your_ssh_password"
    ansible_become: yes
    ansible_become_method: enable
    ansible_become_pass: "your_enable_password"

  tasks:
    - name: Show the running configuration
      cisco.ios.ios_command:
        commands:
          - show running-config
      register: output

    - name: Print the output
      debug:
        var: output.stdout_lines
