---
- name: Get and Save Running Configuration via NETCONF
  hosts: csr
  connection: netconf
  gather_facts: no

  tasks:
    - name: Execute a <get-config> RPC for the native model
      ansible.netcommon.netconf_rpc:
        rpc: get-config
        content: |
          <source>
            <running/>
          </source>
          <filter>
            <native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native"/>
          </filter>
      register: running_config_output

    # --- THIS IS THE FIX ---
    # The set_stats module is used to populate the AWX Artifacts section.
    - name: Expose the running configuration as a job artifact
      ansible.builtin.set_stats:
        data:
          # The key 'running_configuration' is a custom name you choose.
          # The value is the data you want to display.
          running_configuration: "{{ running_config_output.stdout }}"
      # This task must also run on the control node.
      delegate_to: localhost

    - name: Display a confirmation message
      debug:
        msg: "Successfully retrieved the configuration and exposed it as an artifact."
