- name: Create in-memory target host
  hosts: localhost
  gather_facts: no

  vars:
    target_ip: "{{ target_ip }}"
    target_user: "{{ target_user }}"
    target_password: "{{ target_password }}"

  tasks:
    - name: Add target VM dynamically
      add_host:
        name: ubuntu-vm-inline
        ansible_host: "{{ target_ip }}"
        ansible_user: "{{ target_user }}"
        ansible_password: "{{ target_password }}"
        ansible_connection: ssh
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

- name: Run IPsec command inside branch1 container
  hosts: ubuntu-vm-inline
  gather_facts: no

  vars:
    kube_namespace: "net"
    kube_pod: "hub"
    kube_container: "strongswan"

  tasks:
    - name: Run ipsec command
      ansible.builtin.shell: |
        echo "ipsec statusall"
        microk8s kubectl exec -i {{ kube_pod }} -n {{ kube_namespace }} -c {{ kube_container }} -- bash -c "ipsec statusall" | sed '/^Status of IKE charon daemon/d; /^  uptime:/d; /^  malloc:/d; /^  worker threads:/d; /^  loaded plugins:/d'
        echo
      register: ipsec_output
      changed_when: false

    - name: Print raw output
      debug:
        #msg: "{{ ipsec_output.stdout }}"
        msg: "{{ ipsec_output.stdout | replace('\n', ' ') }}"
