---
- name: Install a package on localhost
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: Update apt package index
      ansible.builtin.apt:
        update_cache: yes

    - name: Install figlet package
      ansible.builtin.apt:
        name: figlet
        state: present
