---
- name: Execute commands on Linux VM
  hosts: vms
#  become: yes  # Use sudo privileges if needed
  gather_facts: yes
  vars:
    namespace: "net"
  
  tasks:
    - name: apply branch yaml file
      shell: microk8s kubectl apply -f TEST/branch1.yaml

    - name: Get pods status in namespace
      shell: microk8s kubectl get pods -n {{ namespace }}
      register: kubectl_output
      changed_when: false

    - name: Sleep for 30 seconds
      wait_for:
        timeout: 30
          
    - name: Get pods status in namespace
      shell: microk8s kubectl get pods -n {{ namespace }}
      register: kubectl_output
      changed_when: false
            
    - name: Display kubectl output
      debug:
        msg: "{{ kubectl_output.stdout }}"
        
    - name: Check if 'Running' status exists in output
      set_fact:
        pods_running: "{{ 'Running' in kubectl_output.stdout }}"
        
    - name: Display result of Running status check
      debug:
        msg: |
          Running status found: {{ pods_running }}
          {% if pods_running %}
          ✅ At least one pod is in Running state
          {% else %}
          ❌ No pods are in Running state
          {% endif %}
          
    # - name: Fail if no pods are running (optional)
    #   fail:
    #     msg: "No pods are in Running state in namespace {{ namespace }}"
    #   when: not pods_running
    #   # Comment out the above 3 lines if you don't want the playbook to fail 

