---
- name: Execute commands on Linux VM
  hosts: vms
#  become: yes  # Use sudo privileges if needed
  gather_facts: yes
  vars:
    pod_namespace: "net"
    pod_name: "branch1"
    timeout_seconds: 100
  
  tasks:
    - name: apply branch yaml file
      shell: microk8s kubectl apply -f TEST/branch1.yaml

    - name: Get pods status in namespace
      shell: microk8s kubectl get pods -n {{ pod_namespace }}
      register: kubectl_output
      changed_when: false

    - name: Get initial pod status
      shell: microk8s kubectl get pods -n {{ pod_namespace }} -o wide
      register: initial_status
      failed_when: initial_status.rc != 0
      
    - name: Check current status
      debug:
        msg: |
          Initial pod status:
          {{ initial_status.stdout }}
          
    - name: Determine if pod is already running
      set_fact:
        is_running: "{{ 'Running' in initial_status.stdout }}"
        
    - name: Wait for pod to be in Running state (if not already)
      shell: |
        timeout {{ timeout_seconds }} bash -c '
        while true; do
          status=$(microk8s kubectl get pods -n {{ pod_namespace }} {{ pod_name }} --no-headers | awk "{print \$3}")
          echo "Current status: $status"
          if [ "$status" = "Running" ]; then
            echo "Pod is now Running!"
            microk8s kubectl get pods -n {{ pod_namespace }}
            exit 0
          fi
          sleep 5
        done'
      register: wait_result
      when: not is_running
      
    - name: Display result for already running pod
      shell: microk8s kubectl get pods -n {{ pod_namespace }}
      register: current_status
      when: is_running
      
    - name: Show final status
      debug:
        msg: |
          {% if is_running %}
          Pod was already in Running state:
          {{ current_status.stdout }}
          {% else %}
          Pod monitoring result:
          {{ wait_result.stdout }}
          {% endif %}

    - name: Sleep for 5 seconds
      wait_for:
        timeout: 5
        
    - name: config ipsec tunnels 
      shell: |
        microk8s kubectl exec -n net -c strongswan branch1 -- bash -c "ipsec up hub-inet"
        microk8s kubectl exec -n net -c strongswan branch1 -- bash -c "ipsec up hub-mpls"
#        microk8s kubectl exec -n net -c strongswan branch1 -- bash -c "ipsec up b2-data"

    # - name: Sleep for 30 seconds
    #   wait_for:
    #     timeout: 30

